# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_pyTurbineGeo(object):
    def setupUi(self, pyTurbineGeo):
        pyTurbineGeo.setObjectName("pyTurbineGeo")
        pyTurbineGeo.resize(1354, 867)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pyTurbineGeo.sizePolicy().hasHeightForWidth())
        pyTurbineGeo.setSizePolicy(sizePolicy)
        self.groupBox_31 = QtWidgets.QGroupBox(pyTurbineGeo)
        self.groupBox_31.setGeometry(QtCore.QRect(10, 10, 281, 851))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_31.setFont(font)
        self.groupBox_31.setObjectName("groupBox_31")
        self.label_59 = QtWidgets.QLabel(self.groupBox_31)
        self.label_59.setGeometry(QtCore.QRect(20, 150, 151, 21))
        self.label_59.setObjectName("label_59")
        self.label_63 = QtWidgets.QLabel(self.groupBox_31)
        self.label_63.setGeometry(QtCore.QRect(20, 270, 161, 21))
        self.label_63.setObjectName("label_63")
        self.label_65 = QtWidgets.QLabel(self.groupBox_31)
        self.label_65.setGeometry(QtCore.QRect(20, 330, 161, 21))
        self.label_65.setObjectName("label_65")
        self.label_64 = QtWidgets.QLabel(self.groupBox_31)
        self.label_64.setGeometry(QtCore.QRect(20, 300, 161, 21))
        self.label_64.setObjectName("label_64")
        self.label_67 = QtWidgets.QLabel(self.groupBox_31)
        self.label_67.setGeometry(QtCore.QRect(20, 390, 161, 21))
        self.label_67.setObjectName("label_67")
        self.label_62 = QtWidgets.QLabel(self.groupBox_31)
        self.label_62.setGeometry(QtCore.QRect(20, 240, 171, 21))
        self.label_62.setObjectName("label_62")
        self.label_60 = QtWidgets.QLabel(self.groupBox_31)
        self.label_60.setGeometry(QtCore.QRect(20, 180, 151, 21))
        self.label_60.setObjectName("label_60")
        self.label_66 = QtWidgets.QLabel(self.groupBox_31)
        self.label_66.setGeometry(QtCore.QRect(20, 360, 161, 21))
        self.label_66.setObjectName("label_66")
        self.label_69 = QtWidgets.QLabel(self.groupBox_31)
        self.label_69.setGeometry(QtCore.QRect(20, 450, 161, 21))
        self.label_69.setObjectName("label_69")
        self.label_68 = QtWidgets.QLabel(self.groupBox_31)
        self.label_68.setGeometry(QtCore.QRect(20, 420, 161, 21))
        self.label_68.setObjectName("label_68")
        self.label_61 = QtWidgets.QLabel(self.groupBox_31)
        self.label_61.setGeometry(QtCore.QRect(20, 210, 151, 21))
        self.label_61.setObjectName("label_61")
        self.label_58 = QtWidgets.QLabel(self.groupBox_31)
        self.label_58.setGeometry(QtCore.QRect(20, 30, 151, 21))
        self.label_58.setObjectName("label_58")
        self.label_79 = QtWidgets.QLabel(self.groupBox_31)
        self.label_79.setGeometry(QtCore.QRect(20, 60, 151, 21))
        self.label_79.setObjectName("label_79")
        self.label_82 = QtWidgets.QLabel(self.groupBox_31)
        self.label_82.setGeometry(QtCore.QRect(20, 90, 161, 21))
        self.label_82.setObjectName("label_82")
        self.label_84 = QtWidgets.QLabel(self.groupBox_31)
        self.label_84.setGeometry(QtCore.QRect(20, 540, 161, 21))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.groupBox_31)
        self.label_85.setGeometry(QtCore.QRect(20, 510, 161, 21))
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.groupBox_31)
        self.label_86.setGeometry(QtCore.QRect(20, 480, 161, 21))
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.groupBox_31)
        self.label_87.setGeometry(QtCore.QRect(20, 630, 161, 21))
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.groupBox_31)
        self.label_88.setGeometry(QtCore.QRect(20, 570, 161, 21))
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.groupBox_31)
        self.label_89.setGeometry(QtCore.QRect(20, 600, 161, 21))
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.groupBox_31)
        self.label_90.setGeometry(QtCore.QRect(20, 120, 171, 21))
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.groupBox_31)
        self.label_91.setGeometry(QtCore.QRect(20, 660, 171, 21))
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.groupBox_31)
        self.label_92.setGeometry(QtCore.QRect(20, 690, 191, 21))
        self.label_92.setObjectName("label_92")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 30, 51, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 60, 51, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_7.setGeometry(QtCore.QRect(220, 90, 51, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_8.setGeometry(QtCore.QRect(220, 120, 51, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_10.setGeometry(QtCore.QRect(220, 150, 51, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_11.setGeometry(QtCore.QRect(220, 180, 51, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_12.setGeometry(QtCore.QRect(220, 210, 51, 22))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_13.setGeometry(QtCore.QRect(220, 240, 51, 22))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_14.setGeometry(QtCore.QRect(220, 270, 51, 22))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_15.setGeometry(QtCore.QRect(220, 300, 51, 22))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_16.setGeometry(QtCore.QRect(220, 330, 51, 22))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_17.setGeometry(QtCore.QRect(220, 360, 51, 22))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_18.setGeometry(QtCore.QRect(220, 390, 51, 22))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_19.setGeometry(QtCore.QRect(220, 420, 51, 22))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_20.setGeometry(QtCore.QRect(220, 450, 51, 22))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_21.setGeometry(QtCore.QRect(220, 480, 51, 22))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_22.setGeometry(QtCore.QRect(220, 510, 51, 22))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_23.setGeometry(QtCore.QRect(220, 540, 51, 22))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_24.setGeometry(QtCore.QRect(220, 570, 51, 22))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_25.setGeometry(QtCore.QRect(220, 600, 51, 22))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_26.setGeometry(QtCore.QRect(220, 630, 51, 22))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_27.setGeometry(QtCore.QRect(220, 660, 51, 22))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_28.setGeometry(QtCore.QRect(220, 690, 51, 22))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.groupBox_4 = QtWidgets.QGroupBox(pyTurbineGeo)
        self.groupBox_4.setGeometry(QtCore.QRect(300, 10, 871, 761))
        self.groupBox_4.setObjectName("groupBox_4")

        self.groupBox_2 = QtWidgets.QGroupBox(pyTurbineGeo)
        self.groupBox_2.setGeometry(QtCore.QRect(1180, 220, 163, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_5.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_5.addWidget(self.checkBox_2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_5.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_5.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_5.addWidget(self.checkBox_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.groupBox_12 = QtWidgets.QGroupBox(pyTurbineGeo)
        self.groupBox_12.setGeometry(QtCore.QRect(1180, 10, 161, 201))
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_3.addWidget(self.radioButton_11)
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_3.addWidget(self.radioButton_13)
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_3.addWidget(self.radioButton_12)
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_3.addWidget(self.radioButton_14)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_3.addWidget(self.radioButton)
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout_3.addWidget(self.radioButton_15)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_3.addWidget(self.radioButton_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.layoutWidget_24 = QtWidgets.QWidget(pyTurbineGeo)
        self.layoutWidget_24.setGeometry(QtCore.QRect(870, 800, 431, 44))
        self.layoutWidget_24.setObjectName("layoutWidget_24")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_24)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget_24)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget_24)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget_24)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.groupBox_48 = QtWidgets.QGroupBox(pyTurbineGeo)
        self.groupBox_48.setGeometry(QtCore.QRect(300, 770, 511, 91))
        self.groupBox_48.setObjectName("groupBox_48")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_48)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_48)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_48)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)


        self.label_frontview = QtWidgets.QLabel(self.groupBox_4)
        self.label_frontview.setGeometry(QtCore.QRect(10, 20, 421, 361))
        self.label_frontview.setText("")
        self.label_frontview.setPixmap(QtGui.QPixmap("images/TLP_front.png"))
        self.label_frontview.setScaledContents(True)
        self.label_frontview.setObjectName("label_frontview")
        self.Label_topview = QtWidgets.QLabel(self.groupBox_4)
        self.Label_topview.setGeometry(QtCore.QRect(440, 20, 421, 361))
        self.Label_topview.setText("")
        self.Label_topview.setPixmap(QtGui.QPixmap("images/TLP_top.png"))
        self.Label_topview.setScaledContents(True)
        self.Label_topview.setObjectName("Label_topview")
        self.Label_sideview = QtWidgets.QLabel(self.groupBox_4)
        self.Label_sideview.setGeometry(QtCore.QRect(10, 390, 421, 361))
        self.Label_sideview.setText("")
        self.Label_sideview.setPixmap(QtGui.QPixmap("images/TLP_side.png"))
        self.Label_sideview.setScaledContents(True)
        self.Label_sideview.setObjectName("Label_sideview")
        self.Label_isoview = QtWidgets.QLabel(self.groupBox_4)
        self.Label_isoview.setGeometry(QtCore.QRect(440, 390, 421, 361))
        self.Label_isoview.setText("")
        self.Label_isoview.setPixmap(QtGui.QPixmap("images/TLP_iso.png"))
        self.Label_isoview.setScaledContents(True)
        self.Label_isoview.setObjectName("Label_isoview")


        self.retranslateUi(pyTurbineGeo)
        QtCore.QMetaObject.connectSlotsByName(pyTurbineGeo)

        self.radioButton_11.clicked.connect(self.show_blade)
        self.radioButton_12.clicked.connect(self.show_tower)
        self.radioButton_14.clicked.connect(self.show_turbine)
        self.radioButton_13.clicked.connect(self.show_rotor)
        self.radioButton_15.clicked.connect(self.show_TLP)
        self.radioButton_2.clicked.connect(self.show_Spar)
        self.radioButton.clicked.connect(self.show_SS)

    def retranslateUi(self, pyTurbineGeo):
        _translate = QtCore.QCoreApplication.translate
        pyTurbineGeo.setWindowTitle(_translate("pyTurbineGeo", "pyTurbineGeo"))
        self.groupBox_31.setTitle(_translate("pyTurbineGeo", "Geometry Specifications for Preliminary Design"))
        self.label_59.setText(_translate("pyTurbineGeo", "Blade Chord (m)"))
        self.label_63.setText(_translate("pyTurbineGeo", "Blade PreBend (m)"))
        self.label_65.setText(_translate("pyTurbineGeo", "Blade Root Length (m)"))
        self.label_64.setText(_translate("pyTurbineGeo", "Blade Root Diameter (m)"))
        self.label_67.setText(_translate("pyTurbineGeo", "Blade Chord Length (m)"))
        self.label_62.setText(_translate("pyTurbineGeo", "Blade Absolute Thickness (m)"))
        self.label_60.setText(_translate("pyTurbineGeo", "Blade Twist (rad)"))
        self.label_66.setText(_translate("pyTurbineGeo", "Blade Chord Diameter (m)"))
        self.label_69.setText(_translate("pyTurbineGeo", "Blade Tip Diameter (m)"))
        self.label_68.setText(_translate("pyTurbineGeo", "Blade Midspan Length (m)"))
        self.label_61.setText(_translate("pyTurbineGeo", "Blade Relative Thickness"))
        self.label_58.setText(_translate("pyTurbineGeo", "Number of Blades"))
        self.label_79.setText(_translate("pyTurbineGeo", "Rotor Diameter (m)"))
        self.label_82.setText(_translate("pyTurbineGeo", "Hub Upwind Diameter (m)"))
        self.label_84.setText(_translate("pyTurbineGeo", "Nacelle Width (m)"))
        self.label_85.setText(_translate("pyTurbineGeo", "Nacelle Length (m)"))
        self.label_86.setText(_translate("pyTurbineGeo", "Nacelle Height (m)"))
        self.label_87.setText(_translate("pyTurbineGeo", "Tower Wall Thickness (m)"))
        self.label_88.setText(_translate("pyTurbineGeo", "Tower Height (m)"))
        self.label_89.setText(_translate("pyTurbineGeo", "Tower Outer Diameter (m)"))
        self.label_90.setText(_translate("pyTurbineGeo", "Hub Downwind Diameter (m)"))
        self.label_91.setText(_translate("pyTurbineGeo", "Mesh Density #Radial Panels"))
        self.label_92.setText(_translate("pyTurbineGeo", "Mesh Density #Chordwise Panels"))
        self.lineEdit_2.setText(_translate("pyTurbineGeo", "3"))
        self.lineEdit_4.setText(_translate("pyTurbineGeo", "100"))
        self.lineEdit_7.setText(_translate("pyTurbineGeo", "1"))
        self.lineEdit_8.setText(_translate("pyTurbineGeo", "0.8"))
        self.lineEdit_10.setText(_translate("pyTurbineGeo", "2.2"))
        self.lineEdit_11.setText(_translate("pyTurbineGeo", "0.3"))
        self.lineEdit_12.setText(_translate("pyTurbineGeo", "50"))
        self.lineEdit_13.setText(_translate("pyTurbineGeo", "2.5"))
        self.lineEdit_14.setText(_translate("pyTurbineGeo", "2.5"))
        self.lineEdit_15.setText(_translate("pyTurbineGeo", "3"))
        self.lineEdit_16.setText(_translate("pyTurbineGeo", "15"))
        self.lineEdit_17.setText(_translate("pyTurbineGeo", "6"))
        self.lineEdit_18.setText(_translate("pyTurbineGeo", "50"))
        self.lineEdit_19.setText(_translate("pyTurbineGeo", "45"))
        self.lineEdit_20.setText(_translate("pyTurbineGeo", "1"))
        self.lineEdit_21.setText(_translate("pyTurbineGeo", "2"))
        self.lineEdit_22.setText(_translate("pyTurbineGeo", "2.5"))
        self.lineEdit_23.setText(_translate("pyTurbineGeo", "2"))
        self.lineEdit_24.setText(_translate("pyTurbineGeo", "135"))
        self.lineEdit_25.setText(_translate("pyTurbineGeo", "8"))
        self.lineEdit_26.setText(_translate("pyTurbineGeo", "0.3"))
        self.lineEdit_27.setText(_translate("pyTurbineGeo", "35"))
        self.lineEdit_28.setText(_translate("pyTurbineGeo", "30"))
        self.groupBox_4.setTitle(_translate("pyTurbineGeo", "Geometry Display"))
        self.groupBox_2.setTitle(_translate("pyTurbineGeo", "Options"))
        self.checkBox.setText(_translate("pyTurbineGeo", "Hub"))
        self.checkBox_2.setText(_translate("pyTurbineGeo", "Chord Optimization"))
        self.checkBox_4.setText(_translate("pyTurbineGeo", "Optimization Plots"))
        self.checkBox_5.setText(_translate("pyTurbineGeo", "Geometry Plots"))
        self.checkBox_6.setText(_translate("pyTurbineGeo", "Performance Curve"))
        self.groupBox_12.setTitle(_translate("pyTurbineGeo", "Application"))
        self.radioButton_11.setText(_translate("pyTurbineGeo", "Blade"))
        self.radioButton_13.setText(_translate("pyTurbineGeo", "Rotor"))
        self.radioButton_12.setText(_translate("pyTurbineGeo", "Tower"))
        self.radioButton_14.setText(_translate("pyTurbineGeo", "Turbine"))
        self.radioButton.setText(_translate("pyTurbineGeo", "Semi-Sub Platform"))
        self.radioButton_15.setText(_translate("pyTurbineGeo", "TLP Platform"))
        self.radioButton_2.setText(_translate("pyTurbineGeo", "Spar Platform"))
        self.pushButton_7.setText(_translate("pyTurbineGeo", "Load"))
        self.pushButton_8.setText(_translate("pyTurbineGeo", "Save"))
        self.pushButton_9.setText(_translate("pyTurbineGeo", "Run pyTurbineGeo"))
        self.groupBox_48.setTitle(_translate("pyTurbineGeo", "Write Input Files"))
        self.label_5.setText(_translate("pyTurbineGeo", "Location to Export Wind Turbine File"))

    def show_blade(self):
        self.label_frontview.setPixmap(QtGui.QPixmap("images/Blade_front.png"))
        self.Label_topview.setPixmap(QtGui.QPixmap("images/Blade_top.png"))
        self.Label_sideview.setPixmap(QtGui.QPixmap("images/Blade_side.png"))
        self.Label_isoview.setPixmap(QtGui.QPixmap("images/Blade_iso.png"))

    def show_tower(self):
        self.label_frontview.setPixmap(QtGui.QPixmap("images/Tower_front.png"))
        self.Label_topview.setPixmap(QtGui.QPixmap("images/Tower_top.png"))
        self.Label_sideview.setPixmap(QtGui.QPixmap("images/Tower_side.png"))
        self.Label_isoview.setPixmap(QtGui.QPixmap("images/Tower_iso.png"))

    def show_rotor(self):
        self.label_frontview.setPixmap(QtGui.QPixmap("images/Rotor_front.png"))
        self.Label_topview.setPixmap(QtGui.QPixmap("images/Rotor_top.png"))
        self.Label_sideview.setPixmap(QtGui.QPixmap("images/Rotor_side.png"))
        self.Label_isoview.setPixmap(QtGui.QPixmap("images/Rotor_iso.png"))

    def show_turbine(self):
        self.label_frontview.setPixmap(QtGui.QPixmap("images/Turbine_front.png"))
        self.Label_topview.setPixmap(QtGui.QPixmap("images/Turbine_top.png"))
        self.Label_sideview.setPixmap(QtGui.QPixmap("images/Turbine_side.png"))
        self.Label_isoview.setPixmap(QtGui.QPixmap("images/Turbine_iso.png"))

    def show_TLP(self):
        self.label_frontview.setPixmap(QtGui.QPixmap("images/TLP_front.png"))
        self.Label_topview.setPixmap(QtGui.QPixmap("images/TLP_top.png"))
        self.Label_sideview.setPixmap(QtGui.QPixmap("images/TLP_side.png"))
        self.Label_isoview.setPixmap(QtGui.QPixmap("images/TLP_iso.png"))

    def show_Spar(self):
        self.label_frontview.setPixmap(QtGui.QPixmap("images/Spar_front.png"))
        self.Label_topview.setPixmap(QtGui.QPixmap("images/Spar_top.png"))
        self.Label_sideview.setPixmap(QtGui.QPixmap("images/Spar_side.png"))
        self.Label_isoview.setPixmap(QtGui.QPixmap("images/Spar_iso.png"))

    def show_SS(self):
        self.label_frontview.setPixmap(QtGui.QPixmap("images/SS_front.png"))
        self.Label_topview.setPixmap(QtGui.QPixmap("images/SS_top.png"))
        self.Label_sideview.setPixmap(QtGui.QPixmap("images/SS_side.png"))
        self.Label_isoview.setPixmap(QtGui.QPixmap("images/SS_iso.png"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pyTurbineGeo = QtWidgets.QWizardPage()
    ui = Ui_pyTurbineGeo()
    ui.setupUi(pyTurbineGeo)
    pyTurbineGeo.show()
    sys.exit(app.exec_())

